#!/bin/bash -l
# USAGE: qsub fqdump.qsub <PATH TO LIST OF SRAS> <OUTPUT DIRECTORY> <fasterq-dump arguments>
# Do not use the -O option for output directory, supply output directory as second argument

#$ -P talbot-lab-data
#$ -j y
#$ -pe omp 16

module load sratoolkit

#### PARSER ARGUMENTS ####
# If batch job, use SGE_TASK_ID
if [ -z $SGE_TASK_ID ]
then
    SRA_LIST_PATH=$1
else
    suffix=$((SGE_TASK_ID - 1 ))
    SRA_LIST_PATH=$1_$suffix
fi
OUTDIR=$2
ARGS=${@:3}

# Get SRAs
SRAs=$(cat $SRA_LIST_PATH)

# Prefetch
cmd="prefetch $SRAs"
echo $cmd
eval $cmd

# Fasterq-dump
dumpdir=$(mktemp -d)
cmd="fasterq-dump $SRAs -e $(nproc --all) -O $dumpdir $ARGS"
echo $cmd
eval $cmd

# Gzip files
cmd="gzip $dumpdir"
echo $cmd
eval $cmd

# Move gzipped files to output directory
cmd="mv $dumpdir/*.gz $OUTDIR"
echo $cmd
eval $cmd

# Remove temporary directory
rm -rf $dumpdir