#!/bin/bash -l
# USAGE: qsub fqdump.qsub <NCBI BIOPROJECT ID>
# REQUIRES parallel-fastq-dump
# conda install -c bioconda parallel-fastq-dump


#$ -P talbot-lab-data
#$ -j y

# Import arguments
BIOPROJECT=$1
ARGS=${@:2}

# Load modules
module load entrez-direct

# Make temp directory
chunks=$PWD/chunks
mkdir -p $chunks

# Get SRA list
SRA_LIST=$chunks/sras.txt
cmd="esearch -db sra -query $BIOPROJECT | efetch --format runinfo |cut -d "," -f 1 | sed -n '1d;p' > $SRA_LIST"
echo $cmd
eval $cmd

# Split SRA_LIST into chunks of 16
cmd="split -l 16 -d $SRA_LIST $chunks/chunk_"
echo $cmd
eval $cmd

for chunk in $chunks/chunk_*
do
    cmd="qsub pfqd.qsub $chunk $ARGS"
    echo $cmd
    eval $cmd
done